# Generated by Django 2.2.10 on 2020-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201115_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
