# Generated by Django 2.2.10 on 2020-11-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_userchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='user_choices', to='polls.Choice'),
        ),
    ]
